Hungarian Translation
ncase/mental-health pull request #23
Opened 2022-05-06 16:03 UTC by TBarnus30

I am a Hungarian high school student who made a translation from English-->Hungarian.
---
man this took a while.
Translating the heads in html, then the .md, checking, fixing some stuff, and me being stupid and not knowing how to make a pull request.
There may still be a few typos or mistakes and I am sorry in advance if that happens. I tried my best.
---
Thank you. Thank you Nicky Case, for making awesome games like Adventures with Anxiety and incredible readables like this one. I show my gratitude to you by trying to make a fan-made translation (an amateur one, but still).
---
I sometimes have thoughts like "I think I may have anxiety, but I'm not 100% sure, and what if I'm just overdramatizing everything? I don't have a say in anything that happens in the AwA community because I myself may not have anxiety."
Maybe I overthink things. Maybe I'm emotional.
But I think I might have grown closer to my own wolf while making this translation, and showing that it *does* care about me.
It just wants to protect me.
---
Thank you and sorry for having to read this letter. This is kind of like a vent-letter (if that makes sense?), but i just had to write these down somewhere, even if it's directed to a person I barely even know.
---
I wish you all the best, be it now, or in the future.

Best wishes,
TBarnus30 (and his wolf, probably).
🐺

2022-05-07 08:10 UTC, balazsjonas commented
Don't worry @TBarnus30 , it's a great job
I will check your translation.
Don't you want to squash the the changes into a single commit?


By the way I would add the Hungarian crisis hotlines in addition to or instead of the original. Do you agree, @ncase ?
Eg.[https://egeszsegvonal.gov.hu/maradj-egeszseges/lelkisegely-szolgalatok.html](https://egeszsegvonal.gov.hu/maradj-egeszseges/lelkisegely-szolgalatok.html)

2022-05-07 08:59 UTC, TBarnus30 commented
Thank you for the comment!
Yes, if we could squash it into a single one it would be great.
I'm not really a pro at using Github.
Also yes, we could add Hungarian crisis hotlines to the ones already listed. These are all great additions.

2022-05-07 09:43 UTC, TBarnus30 commented
Okay,
- Added Hungarian crisis hotline page and number,
- Squished commits into one

2022-05-09 07:17 UTC, balazsjonas requested changes
I will continue from here, I have to go to work. Most comments are only suggestions, not mandatory. Just think about it.

2022-05-09 07:17 UTC, balazsjonas commented on hu.html
> +          <a href="#toc_4">9 Bizonyítékkal alátámasztott Mentális Egészségügyi Szokás</a>
Egyszerüen csak "Bizonyítékkal alátámasztott jó szokások", még gondolkodom rajta.

2022-05-09 07:17 UTC, balazsjonas commented on hu.html
> +      <p>🐺 Várjunk, miért dobog a szívünk? Miért nem tudunk lélegezni?! Nem úgy van hogy a családban fut a szívroham??!?! Jaj nekem, ez lenne a vég?!?!?!</p>
dobog --> kalapál, dübörög vagy valami súlyosabb.

2022-05-09 07:17 UTC, balazsjonas commented on hu.html
> +    <p>4 mentális lépés alatt, egy nem megérkező busz miatt 100%-ig <em>azt hittem</em> hogy meg fogok halni.</p>
nem megérkező -> meg nem érkező
esetleg 100%ig helyett "100% biztos voltam benne, hogy"

2022-05-09 07:17 UTC, balazsjonas commented on hu.html
> +    <p>Szóval, ezért nem bíztam soha a mondásban, hogy "bízz a megérzéseidben." Vagy, hogy "az érzelmeid érvényesek." Képzeld el ezt a szituációt:</p>
Esetleg "érzelmeid megalapozottak"?

2022-05-09 07:17 UTC, balazsjonas commented on hu.html
> +      <p>Barát, mondja neked: Értéktelennek érzem magamat. Úgy érzem hogy csak egy teher vagyok mindenki számára. Úgy érzem, hogy mélyen, én egy visszafordíthatatlanul törött, gonosz ember vagyok.</p
törött -> megtört, összetört

2022-05-09 07:17 UTC, balazsjonas commented on hu.html
> +    <p>Ezért, én elhittem azokat a <em>más</em> mondásokat: "Az érzelmek irracionálisak." "Az egyetlen dolog amitől félni kell az maga a félelem." "Ne aggódj, légy boldog!"</p>
mondások -> közghelyeket?

2022-05-09 18:14 UTC, balazsjonas requested changes
to be continued

2022-05-09 18:14 UTC, balazsjonas commented on hu.html
> +    <p>Viszont, ez arra inspirált hogy <em>végre</em> kipróbáljam a pszichoterápiát. Előszőr a <a href="https://en.wikipedia.org/wiki/Cognitive_behavioral_therapy">Kognitív viselkedési terápiát</a> p
Itt határozotta "szorongás" az "aggodalom" helyett.

2022-05-09 18:14 UTC, balazsjonas commented on hu.html
> +    <p>Utána, kipróbáltam egy <a href="https://en.wikipedia.org/wiki/Mindfulness">éberség</a>-alapú terápiát – pontosabban, <a href="https://en.wikipedia.org/wiki/Acceptance_and_commitment_therapy">E
Itt használhatnánk a magyar linket, ha már feltehetően magyarok olvassák, de meghagynám a címkének a mindfulness-t.  Úgy ismertebb

https://hu.wikipedia.org/wiki/Tudatos_jelenl%C3%A9t

és a párja csak egy bekezdés:
https://hu.wikipedia.org/wiki/Tudatos_jelenl%C3%A9t#Elfogad%C3%A1s_%C3%A9s_elk%C3%B6telez%C5%91d%C3%A9s_ter%C3%A1pia

2022-05-09 18:14 UTC, balazsjonas commented on hu.html
> +    <p>Megintcsak, úgy használtam az éberséget mintha csak egy másik mód lenne arra, hogy <em>ne figyeljek oda</em> a félelmemre. A félelem még <em>mindig</em> az ellenségem volt.</p>
inkább "tudatos jelenlét", mint "éberség", ha mindenképp le szeretnénk fordítani a mindfulness-t,

2022-05-09 19:01 UTC, TBarnus30 commented
Köszi a javaslatokat! Szerintem mindegyik nagyszerű, hozzá is adtam azokat a fájlokhoz. (Kivéve a "Bizonyítékkal alátámasztott jó szokások"-at, mert mondtad hogy azon még gondolkodsz.)

2022-08-09 15:19 UTC, merged

2022-08-09 15:21 UTC, ncase commented
Hi @TBarnus30 ! Thank you for your kind words, and putting in all the effort to making this available to more folks. (and thank you @balazsjonas for polishing it up!)

And, uh, sincerest apologies to you both that it took me so long to finally get around to merging the pull request. 😬 My email is a nightmare, a torture device of my own design.